import { useEffect, useRef } from "react";
import type { AutoSaveData, DocumentData, EditorMode } from "@/types/document";
import { migrateStoredDocumentData } from "@/lib/documents/storedDocument";

const STORAGE_KEY = "docsy-autosave-v2";
const LEGACY_STORAGE_KEY = "docsy-autosave";

const isEditorMode = (value: unknown): value is EditorMode =>
  value === "markdown" || value === "latex" || value === "html" || value === "json" || value === "yaml";

const isRecord = (value: unknown): value is Record<string, unknown> =>
  Boolean(value) && typeof value === "object" && !Array.isArray(value);

const hasMeaningfulMetadata = (metadata: DocumentData["metadata"]) => {
  if (!metadata) {
    return false;
  }

  return Boolean(
    metadata.title
    || metadata.description
    || metadata.tags?.length
    || metadata.authors?.length
    || metadata.sourceFiles?.length
    || Object.keys(metadata.labels || {}).length,
  );
};

const isAutoGeneratedBlankDocument = (document: DocumentData) => {
  const primarySourceContent = document.sourceSnapshots?.[document.mode] || "";

  return (document.name || "").trim() === "Untitled"
    && document.content.trim().length === 0
    && primarySourceContent.trim().length === 0
    && !hasMeaningfulMetadata(document.metadata);
};

const getDocumentSignature = (document: DocumentData) => JSON.stringify({
  content: document.content,
  createdAt: document.createdAt,
  metadata: document.metadata || {},
  mode: document.mode,
  name: document.name,
  sourceSnapshot: document.sourceSnapshots?.[document.mode] || "",
  updatedAt: document.updatedAt,
});

const dedupeDocuments = (documents: DocumentData[], activeDocId: string) => {
  const documentsById = new Map<string, DocumentData>();

  for (const document of documents) {
    const previous = documentsById.get(document.id);

    if (!previous || previous.updatedAt <= document.updatedAt) {
      documentsById.set(document.id, document);
    }
  }

  const documentsBySignature = new Map<string, DocumentData>();

  for (const document of documentsById.values()) {
    const signature = getDocumentSignature(document);
    const previous = documentsBySignature.get(signature);

    if (
      !previous
      || document.id === activeDocId
      || (previous.id !== activeDocId && previous.updatedAt <= document.updatedAt)
    ) {
      documentsBySignature.set(signature, document);
    }
  }

  let normalizedDocuments = [...documentsBySignature.values()];
  const blankDrafts = normalizedDocuments.filter((document) => isAutoGeneratedBlankDocument(document));
  const contentDocuments = normalizedDocuments.filter((document) => !isAutoGeneratedBlankDocument(document));

  if (blankDrafts.length === 1 && contentDocuments.length >= 1) {
    const [blankDraft] = blankDrafts;
    const hasNewerContentDocument = contentDocuments.some((document) =>
      document.createdAt >= blankDraft.createdAt && document.updatedAt >= blankDraft.updatedAt);

    if (blankDraft.id !== activeDocId && hasNewerContentDocument) {
      normalizedDocuments = normalizedDocuments.filter((document) => document.id !== blankDraft.id);
    }
  }

  if (normalizedDocuments.length === 0) {
    const fallback = createNewDocument();

    return {
      activeDocId: fallback.id,
      documents: [fallback],
    } satisfies AutoSaveData;
  }

  normalizedDocuments = normalizedDocuments.sort((left, right) => left.createdAt - right.createdAt);

  return {
    activeDocId: normalizedDocuments.some((document) => document.id === activeDocId)
      ? activeDocId
      : normalizedDocuments[0].id,
    documents: normalizedDocuments,
    lastSaved: Date.now(),
    version: 2 as const,
  } satisfies AutoSaveData;
};

const normalizeLegacyDocument = (value: unknown): DocumentData | null => {
  if (!isRecord(value)) {
    return null;
  }

  const mode = isEditorMode(value.mode) ? value.mode : "markdown";

  if (typeof value.id !== "string" || typeof value.name !== "string") {
    return null;
  }

  return migrateStoredDocumentData({
    id: value.id,
    name: value.name,
    mode,
    content: typeof value.content === "string" ? value.content : "",
    createdAt: typeof value.createdAt === "number" ? value.createdAt : Date.now(),
    updatedAt: typeof value.updatedAt === "number" ? value.updatedAt : Date.now(),
    ast: value.ast ?? null,
    metadata: isRecord(value.metadata) ? value.metadata : undefined,
    sourceSnapshots: isRecord(value.sourceSnapshots) ? value.sourceSnapshots as DocumentData["sourceSnapshots"] : undefined,
    storageKind: value.storageKind === "docsy" || value.storageKind === "legacy" ? value.storageKind : undefined,
    tiptapJson: isRecord(value.tiptapJson) ? value.tiptapJson : null,
  });
};

const isAutoSaveData = (value: unknown): value is AutoSaveData =>
  isRecord(value)
  && value.version === 2
  && Array.isArray(value.documents)
  && typeof value.activeDocId === "string"
  && typeof value.lastSaved === "number";

export const createNewDocument = (name = "Untitled", mode: EditorMode = "markdown"): DocumentData => ({
  id: crypto.randomUUID(),
  name,
  mode,
  content: "",
  createdAt: Date.now(),
  updatedAt: Date.now(),
  ast: null,
  metadata: {},
  sourceSnapshots: { [mode]: "" },
  storageKind: "docsy",
  tiptapJson: null,
});

export const migrateLegacyAutoSaveData = (raw: unknown): AutoSaveData | null => {
  if (isAutoSaveData(raw)) {
    return dedupeDocuments(raw.documents.map(migrateStoredDocumentData), raw.activeDocId);
  }

  if (!isRecord(raw) || !Array.isArray(raw.documents) || typeof raw.activeDocId !== "string") {
    return null;
  }

  const documents = raw.documents
    .map(normalizeLegacyDocument)
    .filter((document): document is DocumentData => Boolean(document));

  if (!documents.length) {
    return null;
  }

  return {
    ...dedupeDocuments(documents, raw.activeDocId),
    lastSaved: typeof raw.lastSaved === "number" ? raw.lastSaved : Date.now(),
  };
};

export const loadSavedData = (): AutoSaveData | null => {
  try {
    const nextRaw = localStorage.getItem(STORAGE_KEY);

    if (nextRaw) {
      const migrated = migrateLegacyAutoSaveData(JSON.parse(nextRaw) as unknown);

      if (migrated) {
        localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...migrated, lastSaved: Date.now() }));
        return migrated;
      }
    }

    const legacyRaw = localStorage.getItem(LEGACY_STORAGE_KEY);

    if (!legacyRaw) {
      return null;
    }

    const migrated = migrateLegacyAutoSaveData(JSON.parse(legacyRaw) as unknown);

    if (!migrated) {
      return null;
    }

    localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...migrated, lastSaved: Date.now() }));
    localStorage.removeItem(LEGACY_STORAGE_KEY);

    return migrated;
  } catch {
    return null;
  }
};

export interface AutoSaveWriteSuccess {
  ok: true;
  savedAt: number;
}

export interface AutoSaveWriteFailure {
  ok: false;
  error: string;
}

export type AutoSaveWriteResult = AutoSaveWriteSuccess | AutoSaveWriteFailure;

export const getAutoSaveSnapshotKey = (data: AutoSaveData) => JSON.stringify({
  activeDocId: data.activeDocId,
  documents: data.documents,
  version: data.version,
});

export const saveData = (data: AutoSaveData): AutoSaveWriteResult => {
  const savedAt = Date.now();
  const normalized = dedupeDocuments(data.documents.map(migrateStoredDocumentData), data.activeDocId);

  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify({
      ...normalized,
      version: 2,
      lastSaved: savedAt,
    }));
    return { ok: true, savedAt };
  } catch {
    return {
      error: "Autosave failed because local storage is unavailable or full.",
      ok: false,
    };
  }
};

interface UseAutoSaveOptions {
  onError?: (error: string) => void;
  onSaved?: (savedAt: number) => void;
  onSaving?: () => void;
}

export const useAutoSave = (
  data: AutoSaveData | null,
  intervalMs = 3000,
  options: UseAutoSaveOptions = {},
) => {
  const dataRef = useRef(data);
  const optionsRef = useRef(options);
  const lastSavedSnapshotRef = useRef<string | null>(
    data && data.lastSaved > 0 ? getAutoSaveSnapshotKey(data) : null,
  );

  dataRef.current = data;
  optionsRef.current = options;

  useEffect(() => {
    lastSavedSnapshotRef.current = data && data.lastSaved > 0 ? getAutoSaveSnapshotKey(data) : null;
  }, [data?.lastSaved]);

  useEffect(() => {
    if (!data) return;
    const timer = setInterval(() => {
      if (!dataRef.current) {
        return;
      }

      const snapshotKey = getAutoSaveSnapshotKey(dataRef.current);

      if (snapshotKey === lastSavedSnapshotRef.current) {
        return;
      }

      optionsRef.current.onSaving?.();
      const result = saveData(dataRef.current);

      if (result.ok) {
        lastSavedSnapshotRef.current = snapshotKey;
        optionsRef.current.onSaved?.(result.savedAt);
        return;
      }

      optionsRef.current.onError?.(result.error);
    }, intervalMs);
    return () => clearInterval(timer);
  }, [data, intervalMs]);
};

export type { AutoSaveData, DocumentData };
