import { useEffect, useRef } from "react";
import type { AutoSaveData, DocumentData, EditorMode } from "@/types/document";
import type { WorkspaceBinding } from "@/types/workspace";
import {
  clearAutosavePointer,
  clearAutosaveV3Snapshot,
  readAutosavePointer,
  readAutosaveV3Snapshot,
  writeAutosavePointer,
  writeAutosaveV3Snapshot,
} from "@/lib/documents/autosaveV3Store";
import {
  getAutosaveSnapshotHash,
  readLastSuccessfulAutosaveMarker,
  readUnloadRecoverySnapshot,
  recordAutosaveDebugEvent,
  writeLastSuccessfulAutosaveMarker,
  writeRestoreSelection,
  writeUnloadRecoverySnapshot,
} from "@/lib/documents/autosaveDebug";
import { migrateStoredDocumentData } from "@/lib/documents/storedDocument";

export const DOCSY_AUTOSAVE_STORAGE_KEY = "docsy-autosave-v2";
export const DOCSY_LEGACY_AUTOSAVE_STORAGE_KEY = "docsy-autosave";
export const DOCSY_AUTOSAVE_VERSION = 2 as const;

const isEditorMode = (value: unknown): value is EditorMode =>
  value === "markdown" || value === "latex" || value === "html" || value === "json" || value === "yaml";

const isRecord = (value: unknown): value is Record<string, unknown> =>
  Boolean(value) && typeof value === "object" && !Array.isArray(value);

const normalizeWorkspaceBinding = (value: unknown): WorkspaceBinding | undefined => {
  if (!isRecord(value)) {
    return undefined;
  }

  if (
    value.provider !== "google_drive"
    || value.documentKind !== "google_docs"
    || typeof value.fileId !== "string"
    || typeof value.mimeType !== "string"
    || typeof value.importedAt !== "number"
    || typeof value.syncStatus !== "string"
  ) {
    return undefined;
  }

  return {
    documentKind: "google_docs",
    driveModifiedTime: typeof value.driveModifiedTime === "string" ? value.driveModifiedTime : undefined,
    fileId: value.fileId,
    importedAt: value.importedAt,
    lastSyncedAt: typeof value.lastSyncedAt === "number" ? value.lastSyncedAt : undefined,
    mimeType: value.mimeType,
    provider: "google_drive",
    revisionId: typeof value.revisionId === "string" ? value.revisionId : undefined,
    syncError: typeof value.syncError === "string" ? value.syncError : undefined,
    syncWarnings: Array.isArray(value.syncWarnings)
      ? value.syncWarnings.filter((entry): entry is string => typeof entry === "string" && entry.length > 0)
      : undefined,
    syncStatus: value.syncStatus as WorkspaceBinding["syncStatus"],
  };
};

const hasMeaningfulMetadata = (metadata: DocumentData["metadata"]) => {
  if (!metadata) {
    return false;
  }

  return Boolean(
    metadata.title
    || metadata.description
    || metadata.tags?.length
    || metadata.authors?.length
    || metadata.sourceFiles?.length
    || Object.keys(metadata.labels || {}).length,
  );
};

export const isAutoGeneratedBlankDocument = (document: DocumentData) => {
  const primarySourceContent = document.sourceSnapshots?.[document.mode] || "";

  return (document.name || "").trim() === "Untitled"
    && document.content.trim().length === 0
    && primarySourceContent.trim().length === 0
    && !hasMeaningfulMetadata(document.metadata);
};

export const hasMeaningfulSavedDocuments = (data: AutoSaveData | null | undefined) => {
  if (!data || data.documents.length === 0) {
    return false;
  }

  return !(
    data.documents.length === 1
    && isAutoGeneratedBlankDocument(data.documents[0])
  );
};

const hasMeaningfulRecoveryHint = () => {
  const lastSaveMarker = readLastSuccessfulAutosaveMarker();
  const unloadSnapshot = readUnloadRecoverySnapshot();

  return Boolean(
    (lastSaveMarker?.isMeaningful && lastSaveMarker.lastSaved)
    || hasMeaningfulSavedDocuments(unloadSnapshot),
  );
};

const getDocumentSignature = (document: DocumentData) => JSON.stringify({
  content: document.content,
  createdAt: document.createdAt,
  metadata: document.metadata || {},
  mode: document.mode,
  name: document.name,
  sourceSnapshot: document.sourceSnapshots?.[document.mode] || "",
  updatedAt: document.updatedAt,
});

const shouldPersistLocalFallback = (data: AutoSaveData) => {
  const totalContentLength = data.documents.reduce((sum, document) => (
    sum
    + document.content.length
    + Object.values(document.sourceSnapshots || {}).reduce((sourceSum, source) => sourceSum + (source?.length || 0), 0)
  ), 0);

  return data.documents.length <= 12 && totalContentLength <= 50_000;
};

const dedupeDocuments = (documents: DocumentData[], activeDocId: string): AutoSaveData | null => {
  const documentsById = new Map<string, DocumentData>();

  for (const document of documents) {
    const previous = documentsById.get(document.id);

    if (!previous || previous.updatedAt <= document.updatedAt) {
      documentsById.set(document.id, document);
    }
  }

  const documentsBySignature = new Map<string, DocumentData>();

  for (const document of documentsById.values()) {
    const signature = getDocumentSignature(document);
    const previous = documentsBySignature.get(signature);

    if (
      !previous
      || document.id === activeDocId
      || (previous.id !== activeDocId && previous.updatedAt <= document.updatedAt)
    ) {
      documentsBySignature.set(signature, document);
    }
  }

  let normalizedDocuments = [...documentsBySignature.values()];
  const blankDrafts = normalizedDocuments.filter((document) => isAutoGeneratedBlankDocument(document));
  const contentDocuments = normalizedDocuments.filter((document) => !isAutoGeneratedBlankDocument(document));

  if (blankDrafts.length === 1 && contentDocuments.length >= 1) {
    const [blankDraft] = blankDrafts;
    const hasNewerContentDocument = contentDocuments.some((document) =>
      document.createdAt >= blankDraft.createdAt && document.updatedAt >= blankDraft.updatedAt);

    if (blankDraft.id !== activeDocId && hasNewerContentDocument) {
      normalizedDocuments = normalizedDocuments.filter((document) => document.id !== blankDraft.id);
    }
  }

  if (normalizedDocuments.length === 0) {
    return null;
  }

  normalizedDocuments = normalizedDocuments.sort((left, right) => left.createdAt - right.createdAt);

  return {
    activeDocId: normalizedDocuments.some((document) => document.id === activeDocId)
      ? activeDocId
      : normalizedDocuments[0].id,
    documents: normalizedDocuments,
    lastSaved: Date.now(),
    version: 2 as const,
  } satisfies AutoSaveData;
};

const normalizeLegacyDocument = (value: unknown): DocumentData | null => {
  if (!isRecord(value)) {
    return null;
  }

  const mode = isEditorMode(value.mode) ? value.mode : "markdown";

  if (typeof value.id !== "string" || typeof value.name !== "string") {
    return null;
  }

  return migrateStoredDocumentData({
    id: value.id,
    name: value.name,
    mode,
    content: typeof value.content === "string" ? value.content : "",
    createdAt: typeof value.createdAt === "number" ? value.createdAt : Date.now(),
    updatedAt: typeof value.updatedAt === "number" ? value.updatedAt : Date.now(),
    ast: (value.ast as DocumentData["ast"]) ?? null,
    metadata: isRecord(value.metadata) ? value.metadata : undefined,
    sourceSnapshots: isRecord(value.sourceSnapshots) ? value.sourceSnapshots as DocumentData["sourceSnapshots"] : undefined,
    storageKind: value.storageKind === "docsy" || value.storageKind === "legacy" ? value.storageKind : undefined,
    tiptapJson: isRecord(value.tiptapJson) ? value.tiptapJson : null,
    workspaceBinding: normalizeWorkspaceBinding(value.workspaceBinding),
  });
};

const isAutoSaveData = (value: unknown): value is AutoSaveData =>
  isRecord(value)
  && value.version === 2
  && Array.isArray(value.documents)
  && typeof value.activeDocId === "string"
  && typeof value.lastSaved === "number";

export const createNewDocument = (name = "Untitled", mode: EditorMode = "markdown"): DocumentData => ({
  id: crypto.randomUUID(),
  name,
  mode,
  content: "",
  createdAt: Date.now(),
  updatedAt: Date.now(),
  ast: null,
  metadata: {},
  sourceSnapshots: { [mode]: "" },
  storageKind: "docsy",
  tiptapJson: null,
});

export const migrateLegacyAutoSaveData = (raw: unknown): AutoSaveData | null => {
  if (isAutoSaveData(raw)) {
    return dedupeDocuments(raw.documents.map(migrateStoredDocumentData), raw.activeDocId);
  }

  if (!isRecord(raw) || !Array.isArray(raw.documents) || typeof raw.activeDocId !== "string") {
    return null;
  }

  const documents = raw.documents
    .map(normalizeLegacyDocument)
    .filter((document): document is DocumentData => Boolean(document));

  if (!documents.length) {
    return null;
  }

  const deduped = dedupeDocuments(documents, raw.activeDocId);

  if (!deduped) {
    return null;
  }

  return {
    ...deduped,
    lastSaved: typeof raw.lastSaved === "number" ? raw.lastSaved : Date.now(),
  };
};

interface ReadLocalSavedDataOptions {
  touchLastSaved?: boolean;
}

const readLocalSavedData = ({ touchLastSaved = true }: ReadLocalSavedDataOptions = {}): AutoSaveData | null => {
  try {
    const nextRaw = localStorage.getItem(DOCSY_AUTOSAVE_STORAGE_KEY);

    if (nextRaw) {
      const migrated = migrateLegacyAutoSaveData(JSON.parse(nextRaw) as unknown);

      if (migrated) {
        if (touchLastSaved) {
          localStorage.setItem(DOCSY_AUTOSAVE_STORAGE_KEY, JSON.stringify({ ...migrated, lastSaved: Date.now() }));
        }
        return migrated;
      }
    }

    const legacyRaw = localStorage.getItem(DOCSY_LEGACY_AUTOSAVE_STORAGE_KEY);

    if (!legacyRaw) {
      return null;
    }

    const migrated = migrateLegacyAutoSaveData(JSON.parse(legacyRaw) as unknown);

    if (!migrated) {
      return null;
    }

    if (touchLastSaved) {
      localStorage.setItem(DOCSY_AUTOSAVE_STORAGE_KEY, JSON.stringify({ ...migrated, lastSaved: Date.now() }));
      localStorage.removeItem(DOCSY_LEGACY_AUTOSAVE_STORAGE_KEY);
    }

    return migrated;
  } catch {
    return null;
  }
};

export const loadSavedData = (): AutoSaveData | null =>
  readLocalSavedData({ touchLastSaved: true });

export const hasRecoverableStoredData = () => {
  const localSnapshot = readLocalSavedData({ touchLastSaved: false });
  if (hasMeaningfulSavedDocuments(localSnapshot) || hasMeaningfulRecoveryHint()) {
    return true;
  }

  return !localSnapshot && Boolean(readAutosavePointer());
};

interface SnapshotCandidate {
  data: AutoSaveData;
  source: "local" | "unload" | "v3";
}

const getSnapshotSourceRank = (source: SnapshotCandidate["source"]) => {
  switch (source) {
    case "unload":
      return 3;
    case "local":
      return 2;
    default:
      return 1;
  }
};

const choosePreferredSnapshot = (candidates: SnapshotCandidate[]) => {
  if (candidates.length === 0) {
    return null;
  }

  const meaningfulCandidates = candidates.filter((candidate) => hasMeaningfulSavedDocuments(candidate.data));
  const pool = meaningfulCandidates.length > 0 ? meaningfulCandidates : candidates;

  return [...pool].sort((left, right) => (
    right.data.lastSaved - left.data.lastSaved
    || getSnapshotSourceRank(right.source) - getSnapshotSourceRank(left.source)
  ))[0];
};

const persistLocalFallbackSnapshot = (
  data: AutoSaveData,
  options?: {
    force?: boolean;
  },
) => {
  const shouldWrite = Boolean(options?.force) || shouldPersistLocalFallback(data);

  if (shouldWrite) {
    localStorage.setItem(DOCSY_AUTOSAVE_STORAGE_KEY, JSON.stringify(data));
    return true;
  }

  localStorage.removeItem(DOCSY_AUTOSAVE_STORAGE_KEY);
  return false;
};

export interface HydratedSavedDataResult {
  candidateCount: number;
  data: AutoSaveData | null;
  hadRecoveryHints: boolean;
  isMeaningful: boolean;
  source: "local" | "none" | "unload" | "v3";
}

export const hydrateSavedData = async (): Promise<HydratedSavedDataResult> => {
  const v3Snapshot = (() => {
    const snapshot = readAutosaveV3Snapshot();
    return snapshot;
  })();
  const localSnapshot = readLocalSavedData({ touchLastSaved: false });
  const unloadSnapshot = readUnloadRecoverySnapshot();
  const previousSaveMarker = readLastSuccessfulAutosaveMarker();
  const hadRecoveryHints = hasMeaningfulRecoveryHint();
  const hydratedV3Snapshot = await v3Snapshot;
  const normalizedV3Snapshot = hydratedV3Snapshot
    ? dedupeDocuments(hydratedV3Snapshot.documents.map(migrateStoredDocumentData), hydratedV3Snapshot.activeDocId)
    : null;
  const candidates = [
    unloadSnapshot ? {
      data: {
        ...(dedupeDocuments(unloadSnapshot.documents.map(migrateStoredDocumentData), unloadSnapshot.activeDocId) || {
          activeDocId: unloadSnapshot.activeDocId,
          documents: [],
          lastSaved: unloadSnapshot.lastSaved,
          version: DOCSY_AUTOSAVE_VERSION,
        }),
        lastSaved: unloadSnapshot.lastSaved,
      },
      source: "unload" as const,
    } : null,
    localSnapshot ? { data: localSnapshot, source: "local" as const } : null,
    normalizedV3Snapshot ? {
      data: {
        ...normalizedV3Snapshot,
        lastSaved: hydratedV3Snapshot?.lastSaved ?? normalizedV3Snapshot.lastSaved,
      },
      source: "v3" as const,
    } : null,
  ].filter((candidate): candidate is SnapshotCandidate =>
    Boolean(candidate) && candidate.data.documents.length > 0);
  const preferred = choosePreferredSnapshot(candidates);
  const shouldRejectBlankPreferred = Boolean(
    hadRecoveryHints
    && preferred
    && !hasMeaningfulSavedDocuments(preferred.data),
  );

  if (!preferred || shouldRejectBlankPreferred) {
    writeRestoreSelection({
      contentHash: "none",
      docCount: 0,
      isMeaningful: false,
      lastSaved: null,
      source: "none",
    });
    recordAutosaveDebugEvent("restore_source_selected", {
      candidateCount: candidates.length,
      hadRecoveryHints,
      previousPreferredSource: preferred?.source ?? null,
      previousSaveMarkerHash: previousSaveMarker?.contentHash ?? null,
      source: "none",
    });
    recordAutosaveDebugEvent("hydrate_result", {
      hadRecoveryHints,
      unloadLastSaved: unloadSnapshot?.lastSaved ?? null,
      localLastSaved: localSnapshot?.lastSaved ?? null,
      source: "none",
      v3LastSaved: normalizedV3Snapshot?.lastSaved ?? null,
    });
    return {
      candidateCount: 0,
      data: null,
      hadRecoveryHints,
      isMeaningful: false,
      source: "none",
    };
  }

  const preferredSnapshot = {
    ...preferred.data,
    lastSaved: preferred.data.lastSaved || Date.now(),
    version: DOCSY_AUTOSAVE_VERSION,
  } satisfies AutoSaveData;
  const restoreSelection = {
    contentHash: getAutosaveSnapshotHash(preferredSnapshot),
    docCount: preferredSnapshot.documents.length,
    isMeaningful: hasMeaningfulSavedDocuments(preferredSnapshot),
    lastSaved: preferredSnapshot.lastSaved,
    source: preferred.source,
  } as const;

  try {
    persistLocalFallbackSnapshot(preferredSnapshot);
    writeAutosavePointer({
      activeDocId: preferredSnapshot.activeDocId,
      documentIds: preferredSnapshot.documents.map((document) => document.id),
      lastSaved: preferredSnapshot.lastSaved,
      version: 3,
    });
    localStorage.removeItem(DOCSY_LEGACY_AUTOSAVE_STORAGE_KEY);
  } catch {
    // best effort local fallback alignment
  }

  writeRestoreSelection(restoreSelection);
  recordAutosaveDebugEvent("restore_source_selected", {
    candidateCount: candidates.length,
    contentHash: restoreSelection.contentHash,
    hadRecoveryHints,
    isMeaningful: restoreSelection.isMeaningful,
    lastSaved: restoreSelection.lastSaved,
    previousSaveMarkerHash: previousSaveMarker?.contentHash ?? null,
    source: restoreSelection.source,
  });

  const shouldRefreshV3 = preferred.source !== "v3"
    || !normalizedV3Snapshot
    || normalizedV3Snapshot.lastSaved < preferredSnapshot.lastSaved;

  if (shouldRefreshV3) {
    const migrated = await writeAutosaveV3Snapshot(
      preferredSnapshot,
      {
        dirtyDocumentIds: preferredSnapshot.documents.map((document) => document.id),
        lastSaved: preferredSnapshot.lastSaved,
      },
    );

    if (migrated) {
      writeAutosavePointer({
        activeDocId: preferredSnapshot.activeDocId,
        documentIds: preferredSnapshot.documents.map((document) => document.id),
        lastSaved: preferredSnapshot.lastSaved,
        version: 3,
      });
    }
  }

  recordAutosaveDebugEvent("hydrate_result", {
    docCount: preferredSnapshot.documents.length,
    hadRecoveryHints,
    localLastSaved: localSnapshot?.lastSaved ?? null,
    selectedLastSaved: preferredSnapshot.lastSaved,
    sourceHash: restoreSelection.contentHash,
    source: preferred.source,
    unloadLastSaved: unloadSnapshot?.lastSaved ?? null,
    v3LastSaved: normalizedV3Snapshot?.lastSaved ?? null,
  });

  return {
    candidateCount: candidates.length,
    data: preferredSnapshot,
    hadRecoveryHints,
    isMeaningful: restoreSelection.isMeaningful,
    source: preferred.source,
  };
};

export const clearSavedData = () => {
  try {
    localStorage.removeItem(DOCSY_AUTOSAVE_STORAGE_KEY);
    localStorage.removeItem(DOCSY_LEGACY_AUTOSAVE_STORAGE_KEY);
    clearAutosavePointer();
  } catch {
    // best effort cleanup
  }

  void clearAutosaveV3Snapshot();
};

export interface AutoSaveWriteSuccess {
  ok: true;
  savedAt: number;
}

export interface AutoSaveWriteFailure {
  ok: false;
  error: string;
}

export type AutoSaveWriteResult = AutoSaveWriteSuccess | AutoSaveWriteFailure;
export const isAutoSaveWriteFailure = (result: AutoSaveWriteResult): result is AutoSaveWriteFailure =>
  "error" in result;

export const getAutoSaveSnapshotKey = (data: AutoSaveData) => JSON.stringify({
  activeDocId: data.activeDocId,
  documents: data.documents,
  version: data.version,
});

interface SaveDataOptions {
  dirtyDocumentIds?: string[];
  forceLocalFallback?: boolean;
  reason?: "autosave" | "manual" | "reset" | "pagehide" | "beforeunload";
}

export const saveData = (data: AutoSaveData, options: SaveDataOptions = {}): AutoSaveWriteResult => {
  const savedAt = Date.now();
  const normalized = dedupeDocuments(data.documents.map(migrateStoredDocumentData), data.activeDocId);
  const reason = options.reason ?? "manual";

  if (!normalized) {
    return {
      error: "Autosave skipped because there are no restorable documents.",
      ok: false,
    };
  }

  try {
    const savedSnapshot = {
      ...normalized,
      version: DOCSY_AUTOSAVE_VERSION,
      lastSaved: savedAt,
    } satisfies AutoSaveData;
    const localFallbackWritten = persistLocalFallbackSnapshot(savedSnapshot, {
      force: options.forceLocalFallback,
    });

    const pointer = {
      activeDocId: savedSnapshot.activeDocId,
      documentIds: savedSnapshot.documents.map((document) => document.id),
      lastSaved: savedAt,
      version: 3 as const,
    };

    localStorage.removeItem(DOCSY_LEGACY_AUTOSAVE_STORAGE_KEY);
    writeAutosavePointer(pointer);
    writeLastSuccessfulAutosaveMarker(savedSnapshot, { reason });
    recordAutosaveDebugEvent("autosave_saved", {
      activeDocId: savedSnapshot.activeDocId,
      contentHash: getAutosaveSnapshotHash(savedSnapshot),
      docCount: savedSnapshot.documents.length,
      isMeaningful: hasMeaningfulSavedDocuments(savedSnapshot),
      localFallbackWritten,
      reason,
      savedAt,
    });
    void writeAutosaveV3Snapshot(savedSnapshot, {
      dirtyDocumentIds: options.dirtyDocumentIds,
      lastSaved: savedAt,
    }).then((persisted) => {
      if (!persisted) {
        recordAutosaveDebugEvent("autosave_error", {
          activeDocId: savedSnapshot.activeDocId,
          error: "indexeddb_write_failed",
          reason,
          savedAt,
        });
      }

      if (!persisted && !localFallbackWritten) {
        try {
          persistLocalFallbackSnapshot(savedSnapshot, { force: true });
          writeAutosavePointer(pointer);
        } catch {
          // best effort fallback recovery
        }
      }
    });
    return { ok: true, savedAt };
  } catch {
    recordAutosaveDebugEvent("autosave_error", {
      activeDocId: normalized.activeDocId,
      docCount: normalized.documents.length,
      error: "local_storage_unavailable",
      reason,
    });
    return {
      error: "Autosave failed because local storage is unavailable or full.",
      ok: false,
    };
  }
};

export const saveDataForUnload = (data: AutoSaveData, options: Omit<SaveDataOptions, "forceLocalFallback"> = {}) =>
  (() => {
    const result = saveData(data, {
      ...options,
      forceLocalFallback: true,
    });

    if (!isAutoSaveWriteFailure(result)) {
      writeUnloadRecoverySnapshot({
        ...data,
        lastSaved: result.savedAt,
        version: DOCSY_AUTOSAVE_VERSION,
      });
    }

    return result;
  })();

interface UseAutoSaveOptions {
  getDirtyDocumentIds?: () => string[];
  onError?: (error: string) => void;
  onSaved?: (savedAt: number) => void;
  onSaving?: () => void;
}

export const useAutoSave = (
  data: AutoSaveData | null,
  intervalMs = 3000,
  options: UseAutoSaveOptions = {},
) => {
  const dataRef = useRef(data);
  const optionsRef = useRef(options);
  const lastSavedSnapshotRef = useRef<string | null>(
    data && data.lastSaved > 0 ? getAutoSaveSnapshotKey(data) : null,
  );

  dataRef.current = data;
  optionsRef.current = options;

  useEffect(() => {
    lastSavedSnapshotRef.current = data && data.lastSaved > 0 ? getAutoSaveSnapshotKey(data) : null;
  }, [data?.lastSaved]);

  useEffect(() => {
    if (!data) return;
    const timer = setInterval(() => {
      if (!dataRef.current) {
        return;
      }

      const snapshotKey = getAutoSaveSnapshotKey(dataRef.current);

      if (snapshotKey === lastSavedSnapshotRef.current) {
        return;
      }

      recordAutosaveDebugEvent("autosave_tick", {
        activeDocId: dataRef.current.activeDocId,
        dirtyDocumentCount: optionsRef.current.getDirtyDocumentIds?.().length ?? null,
        docCount: dataRef.current.documents.length,
      });
      optionsRef.current.onSaving?.();
      const result = saveData(dataRef.current, {
        dirtyDocumentIds: optionsRef.current.getDirtyDocumentIds?.(),
        reason: "autosave",
      });

      if (isAutoSaveWriteFailure(result)) {
        optionsRef.current.onError?.(result.error);
        return;
      }

      lastSavedSnapshotRef.current = snapshotKey;
      optionsRef.current.onSaved?.(result.savedAt);
    }, intervalMs);
    return () => clearInterval(timer);
  }, [data, intervalMs]);
};

export type { AutoSaveData, DocumentData };
